on:
  workflow_dispatch:
  push:

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: closehandle/query-pdb:latest

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
